# This GitHub workflow deploys Terraform resources (ML resource config and more)
# defined under mlops-poc/terraform/staging, when PRs are merged into the default branch
name: Terraform Deployment for mlops-poc Staging

on:
  push:
    branches:
      - "main"
    paths:
      - "mlops-poc/terraform/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    working-directory: ./mlops-poc/terraform

jobs:
  staging:
    concurrency: mlops-poc-staging-terraform-job
    runs-on: ubuntu-20.04
    env:
      DATABRICKS_HOST: https://adb-1778171230779412.12.azuredatabricks.net
      ARM_CLIENT_ID: ${{ secrets.stagingAzureSpApplicationId }}
      ARM_TENANT_ID: ${{ secrets.stagingAzureSpTenantId }}s
      ARM_CLIENT_SECRET: ${{ secrets.stagingAzureSpClientSecret }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - uses: actions/checkout@v3
      - name: GET Databricks AAD Token
        run: |
          DATABRICKS_TOKEN=$(curl --fail -X POST -H 'Content-Type: application/x-www-form-urlencoded' \
                                              "https://login.microsoftonline.com/${{ secrets.stagingAzureSpTenantId }}/oauth2/v2.0/token" \
                                              -d "client_id=${{ secrets.stagingAzureSpApplicationId }}" \
                                              -d 'grant_type=client_credentials' \
                                              -d 'scope=2ff814a6-3304-4ab8-85cb-cd0e6f879c1d%2F.default' \
                                              -d "client_secret=${{ secrets.stagingAzureSpClientSecret }}" |  jq -r  '.access_token')
          echo "DATABRICKS_TOKEN=$DATABRICKS_TOKEN" >> "$GITHUB_ENV"
      - name: AZ Login
        run: |
          az login --service-principal -u ${{ secrets.stagingAzureSpApplicationId }} -p ${{ secrets.stagingAzureSpClientSecret }} --tenant ${{ secrets.stagingAzureSpTenantId }}
      - uses: hashicorp/setup-terraform@v1
      - name: Terraform fmt
        id: fmt
        run: terraform -chdir=staging fmt -check
        continue-on-error: true
      - name: Configure Terraform state backend authentication
        run: |
          # Below we assume you've run the setup scripts under the cicd-setup-scripts directory
          # to create an Azure storage container and store its associated Azure ARM key as a Github Actions secret with
          # name ARM_ACCESS_KEY. We set the ARM_ACCESS_KEY environment variable to authenticate to the azurerm
          # backend as described in https://www.terraform.io/language/settings/backends/azurerm
          echo "ARM_ACCESS_KEY=${{secrets.ARM_ACCESS_KEY}}" >> "$GITHUB_ENV"
      - name: Terraform Init
        id: init
        run: terraform -chdir=staging init
      - name: Terraform Validate
        id: validate
        run: terraform -chdir=staging validate
      - name: Terraform Plan
        id: plan
        run: |
          terraform -chdir=staging plan -no-color \
          -var="git_repo_url=${{ github.server_url }}/${{ github.repository }}"
      - name: Terraform Apply
        id: apply
        run: |
          terraform -chdir=staging apply -auto-approve \
          -var="git_repo_url=${{ github.server_url }}/${{ github.repository }}"
      - name: Terraform Output
        id: output
        run: terraform -chdir=staging output -json
      - name: Commit Terraform Output to File
        id: commit
        run: |
          mkdir -p output
          echo '${{ steps.output.outputs.stdout }}' | jq '.' > output/staging.json
          git config --global user.name 'Terraform Output Github Workflow'
          git config --global user.email '<>'
          output=$(git status --porcelain)
          if [ -n "$output" ]
          then
            git add -A
            git commit -m "Commit staging output"
            git push
            git fetch origin release
            git checkout release
            git cherry-pick main
            git push
          fi
